# Generated by Django 4.1.1 on 2022-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='questions',
            field=models.IntegerField(null=True),
        ),
    ]
