# Generated by Django 4.1.1 on 2022-10-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_trivia_average_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='questions',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=50)),
                ('fake_answer', models.CharField(max_length=50)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='trivia.trivia')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
