# Generated by Django 4.1.1 on 2022-10-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_alter_trivia_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='questions',
            field=models.IntegerField(default=2),
        ),
    ]
