# Generated by Django 4.1.1 on 2022-10-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-id',)},
        ),
    ]
