# Generated by Django 4.1.1 on 2022-11-06 17:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia', '0009_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='TriviaFavorite',
        ),
    ]
