# Generated by Django 4.1.1 on 2022-11-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_alter_trivia_questions'),
        ('trivia', '0011_categoryfavorite'),
    ]

    operations = [
    ]
